<a href="https://colab.research.google.com/github/Satyamjat/python.pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

Index(['apple', 'banana', 'papaya', 'orange', 'guava'], dtype='object')

In [ ]:
s.name="numbers"
s.name
s

apple     10
banana    20
papaya    30
orange    40
guava     50
Name: numbers, dtype: int64

In [ ]:
#Indexing
s[0]
s[1:3]

1    20
2    30
Name: numbers, dtype: int64

In [ ]:
# iLoc -> location based indexing
s.iloc[1]
s.iloc[[1,2,4]]
s.iloc[1:4]

1    20
2    30
3    40
dtype: int64

In [ ]:
index=['apple','banana','papaya','orange','guava']
s.index=index
s

apple     10
banana    20
papaya    30
orange    40
guava     50
Name: numbers, dtype: int64

In [ ]:
#loc -> LABEL based indexing
s.loc['apple']
s.loc['apple':'orange']

apple     10
banana    20
papaya    30
orange    40
Name: numbers, dtype: int64

In [ ]:
s.loc[['guava','apple']]

guava    50
apple    10
Name: numbers, dtype: int64

In [ ]:
fruit_protein = {
'Apple':	0.3,
'Banana'	:1.1,
'Orange'	:0.9,
'Mango':	0.8,
'Pineapple':	0.5,
'Papaya':	0.6,
'Guava'	:2.6,
'Strawberry':	0.7,
'Watermelon':0.6,
'Kiwi'	:1.1
                 }

In [ ]:
s2=pd.Series(fruit_protein,name='protein')
s2

Apple         0.3
Banana        1.1
Orange        0.9
Mango         0.8
Pineapple     0.5
Papaya        0.6
Guava         2.6
Strawberry    0.7
Watermelon    0.6
Kiwi          1.1
Name: protein, dtype: float64

In [ ]:
#Conditional selection
s2>1

Apple         False
Banana         True
Orange        False
Mango         False
Pineapple     False
Papaya        False
Guava          True
Strawberry    False
Watermelon    False
Kiwi           True
Name: protein, dtype: bool

In [ ]:
s2[s2>1]

Banana    1.1
Guava     2.6
Kiwi      1.1
Name: protein, dtype: float64

In [ ]:
#not
s2[~(s2>1)]

Apple         0.3
Orange        0.9
Mango         0.8
Pineapple     0.5
Papaya        0.6
Strawberry    0.7
Watermelon    0.6
Name: protein, dtype: float64

In [ ]:
#Modify series

s2['mango']=2.8

In [ ]:
s2

Apple         0.3
Banana        1.1
Orange        0.9
Mango         0.8
Pineapple     0.5
Papaya        0.6
Guava         2.6
Strawberry    0.7
Watermelon    0.6
Kiwi          1.1
mango         2.8
Name: protein, dtype: float64

In [ ]:
#Data frame
data =   {
"Emp ID": [101,102,103,104,105,106,107,108,109,110],
"Emp Name": ["Satyam","Rahul","Priya","Amit","Neha","Karan","Pooja","Arjun","Sneha","Vikram"],
"Salary": [np.nan,38000,52000,47000,41000,60000,39000,55000,43000,62000],
"Dept": ["IT","HR","Finance","IT","Marketing","Finance","HR",np.nan,"Marketing",np.nan]
}
data

{'Emp ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
 'Emp Name': ['Satyam',
  'Rahul',
  'Priya',
  'Amit',
  'Neha',
  'Karan',
  'Pooja',
  'Arjun',
  'Sneha',
  'Vikram'],
 'Salary': [nan,
  38000,
  52000,
  47000,
  41000,
  60000,
  39000,
  55000,
  43000,
  62000],
 'Dept': ['IT',
  'HR',
  'Finance',
  'IT',
  'Marketing',
  'Finance',
  'HR',
  nan,
  'Marketing',
  nan]}

In [ ]:
df=pd.DataFrame(data)
df

   Emp ID Emp Name   Salary       Dept
0     101   Satyam      NaN         IT
1     102    Rahul  38000.0         HR
2     103    Priya  52000.0    Finance
3     104     Amit  47000.0         IT
4     105     Neha  41000.0  Marketing
5     106    Karan  60000.0    Finance
6     107    Pooja  39000.0         HR
7     108    Arjun  55000.0        NaN
8     109    Sneha  43000.0  Marketing
9     110   Vikram  62000.0        NaN

In [ ]:
df.tail(2)

   Emp ID Emp Name   Salary       Dept
8     109    Sneha  43000.0  Marketing
9     110   Vikram  62000.0        NaN

In [ ]:
df.head(3)

   Emp ID Emp Name   Salary     Dept
0     101   Satyam      NaN       IT
1     102    Rahul  38000.0       HR
2     103    Priya  52000.0  Finance

In [ ]:
#loc and iloc
df.iloc[1:3]

   Emp ID Emp Name   Salary     Dept
1     102    Rahul  38000.0       HR
2     103    Priya  52000.0  Finance

In [ ]:
df.loc[1:3,["Emp Name","Dept"]]

  Emp Name     Dept
1    Rahul       HR
2    Priya  Finance
3     Amit       IT

In [ ]:
df[['Salary','Dept']]

    Salary       Dept
0      NaN         IT
1  38000.0         HR
2  52000.0    Finance
3  47000.0         IT
4  41000.0  Marketing
5  60000.0    Finance
6  39000.0         HR
7  55000.0        NaN
8  43000.0  Marketing
9  62000.0        NaN

In [ ]:
#df.drop("Dept",axis=1) #for permananent delete the coloumn   (inplace=True

In [ ]:
df

   Emp ID Emp Name   Salary       Dept
0     101   Satyam      NaN         IT
1     102    Rahul  38000.0         HR
2     103    Priya  52000.0    Finance
3     104     Amit  47000.0         IT
4     105     Neha  41000.0  Marketing
5     106    Karan  60000.0    Finance
6     107    Pooja  39000.0         HR
7     108    Arjun  55000.0        NaN
8     109    Sneha  43000.0  Marketing
9     110   Vikram  62000.0        NaN

In [ ]:
df.shape

(10, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Emp ID    10 non-null     int64
 1   Emp Name  10 non-null     object
 2   Salary    9 non-null      float64
 3   Dept      8 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [ ]:
df.describe()

          Emp ID        Salary
count   10.00000      9.000000
mean   105.50000  48555.555556
std      3.02765   9070.709883
min    101.00000  38000.000000
25%    103.25000  41000.000000
50%    105.50000  47000.000000
75%    107.75000  55000.000000
max    110.00000  62000.000000

In [ ]:
#Renaming columns
df["Salary"] = df["Salary"] + 5000

In [ ]:
# Changing value

# df.loc[df["Emp Name"] == "Satyam", "Salary"] = 50000

#df.loc[df["Emp Name"]=="Satyam","Sal"]=43000
#df.loc[df["Emp Name "]=="Satyam","Sal"]=np.nan

In [ ]:
df

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam  62000.0         IT            NaN
1     102     Yash  53000.0         HR        44234.0
2     103    Priya  67000.0    Finance        58234.0
3     104     Amit  62000.0         IT        53234.0
4     105     Neha  56000.0  Marketing        47234.0
5     106    Karan  75000.0    Finance        66234.0
6     107    Pooja  54000.0         HR        45234.0
7     108    Arjun  70000.0        NaN        61234.0
8     109    Sneha  58000.0  Marketing        49234.0
9     110   Vikram  77000.0        NaN        68234.0

In [ ]:
df.drop(columns='Increased Sal',inplace=True)

In [ ]:
df

   Emp ID Emp Name   Salary       Dept
0     101   Satyam  62000.0         IT
1     102     Yash  53000.0         HR
2     103    Priya  67000.0    Finance
3     104     Amit  62000.0         IT
4     105     Neha  56000.0  Marketing
5     106    Karan  75000.0    Finance
6     107    Pooja  54000.0         HR
7     108    Arjun  70000.0        NaN
8     109    Sneha  58000.0  Marketing
9     110   Vikram  77000.0        NaN

In [ ]:
df.rename(columns ={ "Sal":"Salll"} , inplace=True)

In [ ]:
df

   Emp ID Emp Name   Salary       Dept
0     101   Satyam  62000.0         IT
1     102     Yash  53000.0         HR
2     103    Priya  67000.0    Finance
3     104     Amit  62000.0         IT
4     105     Neha  56000.0  Marketing
5     106    Karan  75000.0    Finance
6     107    Pooja  54000.0         HR
7     108    Arjun  70000.0        NaN
8     109    Sneha  58000.0  Marketing
9     110   Vikram  77000.0        NaN

In [ ]:
#unique
#df["Sal"].unique()

In [ ]:
df["Dept"].value_counts()

Dept
IT           2
HR           2
Finance      2
Marketing    2
Name: count, dtype: int64

In [ ]:
#Broadvcastint and adding new cloumn in table


df["Increased Sal"] =df["Salary"] +1234

In [ ]:
df

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam      NaN         IT            NaN
1     102    Rahul  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0        NaN        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0        NaN        68234.0

In [ ]:
df.isnull().sum()

Emp ID           0
Emp Name         0
Salary           1
Dept             2
Increased Sal    1
dtype: int64

In [ ]:
df

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam      NaN         IT            NaN
1     102    Rahul  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0        NaN        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0        NaN        68234.0

In [ ]:
df.dropna(how ="all") ## if we use "any" then if only one null value even though it will delete the row!!

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam      NaN         IT            NaN
1     102    Rahul  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0        NaN        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0        NaN        68234.0

In [ ]:
df.fillna(0)

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam      0.0         IT            0.0
1     102    Rahul  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0          0        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0          0        68234.0

In [ ]:
df

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam      NaN         IT            NaN
1     102    Rahul  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0        NaN        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0        NaN        68234.0

In [ ]:
df["Salary"].fillna(df["Salary"].median(),inplace=True) # median

/tmp/ipykernel_8394/3615202175.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].median(),inplace=True) # median

In [ ]:
df

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam  52000.0         IT            NaN
1     102    Rahul  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0        NaN        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0        NaN        68234.0

In [ ]:
df["Emp Name"] = df["Emp Name"].replace("Rahul","Yash")

In [ ]:
df

   Emp ID Emp Name   Salary       Dept  Increased Sal
0     101   Satyam  52000.0         IT            NaN
1     102     Yash  43000.0         HR        44234.0
2     103    Priya  57000.0    Finance        58234.0
3     104     Amit  52000.0         IT        53234.0
4     105     Neha  46000.0  Marketing        47234.0
5     106    Karan  65000.0    Finance        66234.0
6     107    Pooja  44000.0         HR        45234.0
7     108    Arjun  60000.0        NaN        61234.0
8     109    Sneha  48000.0  Marketing        49234.0
9     110   Vikram  67000.0        NaN        68234.0

In [ ]:
data1={
"Emp ID": [101,102,103,104,105,106,107,108,108,110],
"Emp Name": ["Satyam","Rahul","Priya","Amit",None,"Karan","Pooja","Arjun","Arjun","Vikram"],
"Salary": [45000,38000,None,47000,41000,60000,39000,55000,55000,None],
"Dept": ["IT","HR","Finance","IT","Marketing","Finance",None,"IT","IT","Management"]
}

In [ ]:
df1=pd.DataFrame(data1)
df1

   Emp ID Emp Name   Salary        Dept
0     101   Satyam  45000.0          IT
1     102    Rahul  38000.0          HR
2     103    Priya      NaN     Finance
3     104     Amit  47000.0          IT
4     105     None  41000.0   Marketing
5     106    Karan  60000.0     Finance
6     107    Pooja  39000.0        None
7     108    Arjun  55000.0          IT
8     108    Arjun  55000.0          IT
9     110   Vikram      NaN  Management

In [ ]:
df1_dup = df1[df1.duplicated()]
df1_dup

   Emp ID Emp Name   Salary Dept
8     108    Arjun  55000.0   IT

In [ ]:
df1=df1.drop_duplicates()

In [ ]:
df1

   Emp ID Emp Name   Salary        Dept
0     101   Satyam  45000.0          IT
1     102    Rahul  38000.0          HR
2     103    Priya      NaN     Finance
3     104     Amit  47000.0          IT
4     105     None  41000.0   Marketing
5     106    Karan  60000.0     Finance
6     107    Pooja  39000.0        None
7     108    Arjun  55000.0          IT
9     110   Vikram      NaN  Management

In [ ]:
#df1["Salary"]=df1["Salary"].apply(lambda x : x/10 if x>50000 else x)

In [ ]:
df1

   Emp ID Emp Name   Salary        Dept
0     101   Satyam  45000.0          IT
1     102    Rahul  38000.0          HR
2     103    Priya      NaN     Finance
3     104     Amit  47000.0          IT
4     105     None  41000.0   Marketing
5     106    Karan  60000.0     Finance
6     107    Pooja  39000.0        None
7     108    Arjun  55000.0          IT
9     110   Vikram      NaN  Management

In [ ]:
df1["Salary"].fillna(df1["Salary"].median(),inplace=True)

/tmp/ipykernel_8394/1637016167.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1["Salary"].fillna(df1["Salary"].median(),inplace=True)
/tmp/ipykernel_8394/1637016167.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["Salary"].fillna(df1["Salary"].median(),inplace=True)

In [ ]:
df1

   Emp ID Emp Name   Salary        Dept
0     101   Satyam  45000.0          IT
1     102    Rahul  38000.0          HR
2     103    Priya  45000.0     Finance
3     104     Amit  47000.0          IT
4     105     None  41000.0   Marketing
5     106    Karan  60000.0     Finance
6     107    Pooja  39000.0        None
7     108    Arjun  55000.0          IT
9     110   Vikram  45000.0  Management